<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="8.0.0" PrivateAssets="all" />
    <PackageReference Include="Microsoft.ClearScript.V8" Version="7.5.0" />
    <PackageReference Include="Microsoft.ClearScript.V8.Native.win-x64" Version="7.5.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.3.0" />
	<PackageReference Include="NUnit" Version="4.5.0" />
	<PackageReference Include="NUnit.Analyzers" Version="4.11.2" PrivateAssets="all" />
    <PackageReference Include="NUnit3TestAdapter" Version="6.1.0" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="NUnit.Framework" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sarifintown.AgentEngine\Sarifintown.AgentEngine.csproj" />
  </ItemGroup>

<ItemGroup>
	<Content Include="..\Sarifintown\wwwroot\js\tree-sitter\**\*.*" Link="tree-sitter\%(RecursiveDir)%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
</ItemGroup>

</Project>
