<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
	<FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.*" PrivateAssets="all" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.*" />
    <PackageReference Include="Microsoft.Playwright.NUnit" Version="1.*" />
    <PackageReference Include="NUnit" Version="4.*" />
    <PackageReference Include="NUnit.Analyzers" Version="4.*" PrivateAssets="all" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.*" />
    <PackageReference Include="bunit" Version="2.*" />
    <PackageReference Include="FluentAssertions" Version="8.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sarifintown\Sarifintown.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="NUnit.Framework" />
  </ItemGroup>

</Project>
