# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET with Playwright Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4.2.0
      with:
        dotnet-version: 9.0.x
    - name: Restore dotnet dependencies
      run: dotnet restore
    - name: Install npm dependencies
      run: npm install -D @playwright/test@latest
    - name: Install playwright browsers
      run: npx playwright install --with-deps

    - name: Build
      run: dotnet build --no-restore
    #- name: Test
    #  run: dotnet test --no-build --verbosity normal

    - name: Run .NET tests
      run: dotnet test Sarifintown.Tests/Sarifintown.Tests.csproj --configuration Release --no-build --verbosity normal
